import React from 'react'
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
  Font
} from '@react-pdf/renderer'
import { formatDate, formatCurrency } from './utils.js'

// Register fonts for better typography
// Font.register({
//   family: 'Open Sans',
//   fonts: [
//     { src: 'https://fonts.googleapis.com/css?family=Open+Sans:400,600' },
//   ]
// })

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    padding: 40,
    fontSize: 10,
    fontFamily: 'Helvetica'
  },
  header: {
    flexDirection: 'row',
    marginBottom: 30,
    paddingBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: '#3B82F6',
    borderBottomStyle: 'solid'
  },
  headerLeft: {
    flex: 1
  },
  headerRight: {
    alignItems: 'flex-end'
  },
  logo: {
    fontSize: 24,
    fontFamily: 'Helvetica-Bold',
    color: '#3B82F6',
    marginBottom: 5
  },
  companyInfo: {
    fontSize: 9,
    color: '#6B7280',
    lineHeight: 1.4
  },
  title: {
    fontSize: 20,
    fontFamily: 'Helvetica-Bold',
    color: '#1F2937',
    marginBottom: 20,
    textAlign: 'center'
  },
  subtitle: {
    fontSize: 14,
    fontFamily: 'Helvetica-Bold',
    color: '#374151',
    marginBottom: 10,
    marginTop: 20
  },
  sectionHeader: {
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
    color: '#1F2937',
    marginBottom: 8,
    marginTop: 15,
    paddingBottom: 5,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    borderBottomStyle: 'solid'
  },
  row: {
    flexDirection: 'row',
    marginBottom: 8,
    alignItems: 'center'
  },
  label: {
    fontSize: 9,
    color: '#6B7280',
    fontFamily: 'Helvetica-Bold',
    width: 80,
    marginRight: 10
  },
  value: {
    fontSize: 9,
    color: '#1F2937',
    flex: 1
  },
  table: {
    marginTop: 15,
    marginBottom: 15
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#F3F4F6',
    padding: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#D1D5DB',
    borderBottomStyle: 'solid'
  },
  tableRow: {
    flexDirection: 'row',
    padding: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: '#E5E7EB',
    borderBottomStyle: 'solid'
  },
  tableRowAlt: {
    flexDirection: 'row',
    padding: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: '#E5E7EB',
    borderBottomStyle: 'solid',
    backgroundColor: '#F9FAFB'
  },
  tableCell: {
    fontSize: 8,
    color: '#374151',
    padding: 2
  },
  tableCellHeader: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    color: '#1F2937',
    padding: 2
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 15
  },
  gridItem: {
    width: '50%',
    padding: 5,
    marginBottom: 10
  },
  card: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderStyle: 'solid',
    borderRadius: 4,
    padding: 12,
    marginBottom: 10,
    backgroundColor: '#FAFAFA'
  },
  badge: {
    backgroundColor: '#3B82F6',
    color: 'white',
    fontSize: 7,
    padding: 3,
    borderRadius: 2,
    marginRight: 5,
    textAlign: 'center'
  },
  badgeSuccess: {
    backgroundColor: '#10B981'
  },
  badgeWarning: {
    backgroundColor: '#F59E0B'
  },
  badgeError: {
    backgroundColor: '#EF4444'
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    color: '#6B7280',
    fontSize: 8,
    borderTopWidth: 0.5,
    borderTopColor: '#E5E7EB',
    borderTopStyle: 'solid',
    paddingTop: 10
  },
  pageNumber: {
    position: 'absolute',
    fontSize: 8,
    bottom: 20,
    left: 0,
    right: 0,
    textAlign: 'center',
    color: '#9CA3AF'
  }
})

// Header component for all PDFs
const PDFHeader = ({ title, subtitle, organizationName = "Shot Builder" }) => (
  <View style={styles.header}>
    <View style={styles.headerLeft}>
      <Text style={styles.logo}>{organizationName}</Text>
      <Text style={styles.companyInfo}>Professional Photo Production Management</Text>
      <Text style={styles.companyInfo}>Generated on {formatDate(new Date())}</Text>
    </View>
    <View style={styles.headerRight}>
      <Text style={styles.title}>{title}</Text>
      {subtitle && <Text style={styles.companyInfo}>{subtitle}</Text>}
    </View>
  </View>
)

// Footer component
const PDFFooter = ({ pageInfo }) => (
  <View style={styles.footer}>
    <Text>This document was generated by Shot Builder - Professional Photo Production Management System</Text>
    <Text style={styles.pageNumber} render={({ pageNumber, totalPages }) => 
      `Page ${pageNumber} of ${totalPages}`
    } fixed />
  </View>
)

// Shot List PDF Document
export const ShotListPDF = ({ 
  shots, 
  selectedFields, 
  options,
  projectName,
  organizationName 
}) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <PDFHeader 
        title="Shot List Export"
        subtitle={projectName ? `Project: ${projectName}` : `${shots.length} shots selected`}
        organizationName={organizationName}
      />

      {options.includesSummary && (
        <View>
          <Text style={styles.subtitle}>Export Summary</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Total Shots:</Text>
            <Text style={styles.value}>{shots.length}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Export Date:</Text>
            <Text style={styles.value}>{formatDate(new Date())}</Text>
          </View>
          {projectName && (
            <View style={styles.row}>
              <Text style={styles.label}>Project:</Text>
              <Text style={styles.value}>{projectName}</Text>
            </View>
          )}
        </View>
      )}

      {/* Shot List Table */}
      <Text style={styles.sectionHeader}>Shot Details</Text>
      <View style={styles.table}>
        {/* Table Header */}
        <View style={styles.tableHeader}>
          {selectedFields.includes('name') && (
            <Text style={[styles.tableCellHeader, { width: '25%' }]}>Shot Name</Text>
          )}
          {selectedFields.includes('type') && (
            <Text style={[styles.tableCellHeader, { width: '15%' }]}>Type</Text>
          )}
          {selectedFields.includes('status') && (
            <Text style={[styles.tableCellHeader, { width: '12%' }]}>Status</Text>
          )}
          {selectedFields.includes('date') && (
            <Text style={[styles.tableCellHeader, { width: '15%' }]}>Scheduled</Text>
          )}
          {selectedFields.includes('products') && (
            <Text style={[styles.tableCellHeader, { width: '10%' }]}>Products</Text>
          )}
          {selectedFields.includes('talent') && (
            <Text style={[styles.tableCellHeader, { width: '10%' }]}>Talent</Text>
          )}
          {selectedFields.includes('location') && (
            <Text style={[styles.tableCellHeader, { width: '13%' }]}>Location</Text>
          )}
        </View>

        {/* Table Rows */}
        {shots.map((shot, index) => (
          <View key={shot.id} style={index % 2 === 0 ? styles.tableRow : styles.tableRowAlt}>
            {selectedFields.includes('name') && (
              <Text style={[styles.tableCell, { width: '25%' }]}>{shot.name}</Text>
            )}
            {selectedFields.includes('type') && (
              <Text style={[styles.tableCell, { width: '15%' }]}>{shot.type || 'N/A'}</Text>
            )}
            {selectedFields.includes('status') && (
              <Text style={[styles.tableCell, { width: '12%' }]}>{shot.status}</Text>
            )}
            {selectedFields.includes('date') && (
              <Text style={[styles.tableCell, { width: '15%' }]}>
                {shot.scheduledDate ? formatDate(shot.scheduledDate) : 'Unscheduled'}
              </Text>
            )}
            {selectedFields.includes('products') && (
              <Text style={[styles.tableCell, { width: '10%' }]}>{shot.productIds?.length || 0}</Text>
            )}
            {selectedFields.includes('talent') && (
              <Text style={[styles.tableCell, { width: '10%' }]}>{shot.talentIds?.length || 0}</Text>
            )}
            {selectedFields.includes('location') && (
              <Text style={[styles.tableCell, { width: '13%' }]}>
                {shot.locationId ? 'Assigned' : 'TBD'}
              </Text>
            )}
          </View>
        ))}
      </View>

      {/* Detailed Shot Information */}
      {options.includeDetails && (
        <View wrap={false}>
          <Text style={styles.sectionHeader}>Detailed Shot Information</Text>
          {shots.slice(0, 10).map((shot) => ( // Limit to 10 for space
            <View key={shot.id} style={styles.card}>
              <Text style={[styles.tableCellHeader, { marginBottom: 5 }]}>{shot.name}</Text>
              {shot.description && (
                <View style={styles.row}>
                  <Text style={styles.label}>Description:</Text>
                  <Text style={styles.value}>{shot.description}</Text>
                </View>
              )}
              {shot.notes && (
                <View style={styles.row}>
                  <Text style={styles.label}>Notes:</Text>
                  <Text style={styles.value}>{shot.notes}</Text>
                </View>
              )}
              {shot.priority && (
                <View style={styles.row}>
                  <Text style={styles.label}>Priority:</Text>
                  <Text style={styles.value}>{shot.priority}</Text>
                </View>
              )}
            </View>
          ))}
          {shots.length > 10 && (
            <Text style={styles.value}>... and {shots.length - 10} more shots</Text>
          )}
        </View>
      )}

      <PDFFooter />
    </Page>
  </Document>
)

// Inventory/Pull Request PDF Document  
export const InventoryPDF = ({ 
  pullRequest, 
  items, 
  products,
  selectedFields,
  options,
  organizationName 
}) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <PDFHeader 
        title="Inventory Pull Request"
        subtitle={`PR #${pullRequest.number} - ${pullRequest.projectName}`}
        organizationName={organizationName}
      />

      {/* Pull Request Information */}
      <View>
        <Text style={styles.subtitle}>Request Information</Text>
        <View style={styles.grid}>
          <View style={styles.gridItem}>
            <View style={styles.row}>
              <Text style={styles.label}>PR Number:</Text>
              <Text style={styles.value}>{pullRequest.number}</Text>
            </View>
            <View style={styles.row}>
              <Text style={styles.label}>Status:</Text>
              <Text style={styles.value}>{pullRequest.status}</Text>
            </View>
            <View style={styles.row}>
              <Text style={styles.label}>Priority:</Text>
              <Text style={styles.value}>{pullRequest.priority}</Text>
            </View>
          </View>
          <View style={styles.gridItem}>
            <View style={styles.row}>
              <Text style={styles.label}>Created:</Text>
              <Text style={styles.value}>{formatDate(pullRequest.createdAt)}</Text>
            </View>
            <View style={styles.row}>
              <Text style={styles.label}>Requested By:</Text>
              <Text style={styles.value}>{pullRequest.createdBy?.name || 'Unknown'}</Text>
            </View>
            <View style={styles.row}>
              <Text style={styles.label}>Total Items:</Text>
              <Text style={styles.value}>{items.length}</Text>
            </View>
          </View>
        </View>
      </View>

      {/* Items Table */}
      <Text style={styles.sectionHeader}>Requested Items</Text>
      <View style={styles.table}>
        {/* Table Header */}
        <View style={styles.tableHeader}>
          {selectedFields.includes('product') && (
            <Text style={[styles.tableCellHeader, { width: '30%' }]}>Product</Text>
          )}
          {selectedFields.includes('styleNumber') && (
            <Text style={[styles.tableCellHeader, { width: '15%' }]}>Style #</Text>
          )}
          {selectedFields.includes('quantity') && (
            <Text style={[styles.tableCellHeader, { width: '10%' }]}>Qty Req</Text>
          )}
          {selectedFields.includes('quantityPicked') && (
            <Text style={[styles.tableCellHeader, { width: '10%' }]}>Qty Pick</Text>
          )}
          {selectedFields.includes('status') && (
            <Text style={[styles.tableCellHeader, { width: '12%' }]}>Status</Text>
          )}
          {selectedFields.includes('notes') && (
            <Text style={[styles.tableCellHeader, { width: '23%' }]}>Notes</Text>
          )}
        </View>

        {/* Table Rows */}
        {items.map((item, index) => {
          const product = products.find(p => p.id === item.productId) || {}
          return (
            <View key={item.id || index} style={index % 2 === 0 ? styles.tableRow : styles.tableRowAlt}>
              {selectedFields.includes('product') && (
                <Text style={[styles.tableCell, { width: '30%' }]}>
                  {product.name || 'Unknown Product'}
                </Text>
              )}
              {selectedFields.includes('styleNumber') && (
                <Text style={[styles.tableCell, { width: '15%' }]}>
                  {product.style_number || 'N/A'}
                </Text>
              )}
              {selectedFields.includes('quantity') && (
                <Text style={[styles.tableCell, { width: '10%' }]}>{item.quantity}</Text>
              )}
              {selectedFields.includes('quantityPicked') && (
                <Text style={[styles.tableCell, { width: '10%' }]}>
                  {item.response?.quantityPicked || 0}
                </Text>
              )}
              {selectedFields.includes('status') && (
                <Text style={[styles.tableCell, { width: '12%' }]}>
                  {item.response?.status || 'Pending'}
                </Text>
              )}
              {selectedFields.includes('notes') && (
                <Text style={[styles.tableCell, { width: '23%' }]}>
                  {item.response?.notes || item.notes || '—'}
                </Text>
              )}
            </View>
          )
        })}
      </View>

      {/* Summary Statistics */}
      {options.includeSummary && (
        <View>
          <Text style={styles.sectionHeader}>Fulfillment Summary</Text>
          <View style={styles.grid}>
            <View style={styles.gridItem}>
              <View style={styles.row}>
                <Text style={styles.label}>Items Requested:</Text>
                <Text style={styles.value}>{items.length}</Text>
              </View>
              <View style={styles.row}>
                <Text style={styles.label}>Items Fulfilled:</Text>
                <Text style={styles.value}>
                  {items.filter(item => item.response?.status === 'fulfilled').length}
                </Text>
              </View>
            </View>
            <View style={styles.gridItem}>
              <View style={styles.row}>
                <Text style={styles.label}>Items Partial:</Text>
                <Text style={styles.value}>
                  {items.filter(item => item.response?.status === 'partial').length}
                </Text>
              </View>
              <View style={styles.row}>
                <Text style={styles.label}>Items Substituted:</Text>
                <Text style={styles.value}>
                  {items.filter(item => item.response?.status === 'substituted').length}
                </Text>
              </View>
            </View>
          </View>
        </View>
      )}

      {/* Substitutions Details */}
      {options.includeSubstitutions && (
        <View>
          <Text style={styles.sectionHeader}>Substitutions & Special Notes</Text>
          {items.filter(item => item.response?.substitution || item.response?.notes).map((item, index) => {
            const product = products.find(p => p.id === item.productId) || {}
            return (
              <View key={index} style={styles.card}>
                <Text style={styles.tableCellHeader}>{product.name}</Text>
                {item.response?.substitution && (
                  <View style={styles.row}>
                    <Text style={styles.label}>Substitution:</Text>
                    <Text style={styles.value}>{item.response.substitution}</Text>
                  </View>
                )}
                {item.response?.notes && (
                  <View style={styles.row}>
                    <Text style={styles.label}>Notes:</Text>
                    <Text style={styles.value}>{item.response.notes}</Text>
                  </View>
                )}
              </View>
            )
          })}
        </View>
      )}

      <PDFFooter />
    </Page>
  </Document>
)