# Minimal allowlist to reduce noise during initial rollout.
# We will tighten rules and remove broad exclusions once signal stabilizes.

[allowlist]
description = "Temporary allowlist for known non-secret files"
paths = [
  "firebase-debug\\.log$",
  "shot_builder_patch\\.diff$",
  # Test files may contain strings like "SECRET" or token-shaped fixtures.
  "src/.*/__tests__/.*",
]
