export const demoUser = {
  id: "demo-user",
  name: "Avery Producer",
  email: "avery.producer@example.com",
  role: "producer",
  avatarUrl: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=80&q=60",
};

export const demoProducts = [
  {
    id: "prod-linen-set",
    name: "Linen Co-ord Set with Oversized Belted Shirt",
    styleName: "Citrus Linen Capsule",
    colourName: "Sunlit Citrus",
    category: "Sets / Capsule",
    skuCode: "LN-221",
    heroImage: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=520&q=60",
    tags: ["spring", "hero", "lookbook", "long-form-name"],
  },
  {
    id: "prod-denim-jacket",
    name: "Denim Chore Jacket with Contrast Stitching and Lining",
    styleName: "Washed Denim",
    colourName: "Stone",
    category: "Outerwear",
    skuCode: "DN-034",
    heroImage: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=520&q=60",
    tags: ["layering"],
  },
  {
    id: "prod-knit-dress",
    name: "Rib Knit Dress",
    styleName: "Column",
    colourName: "Sage",
    category: "Dresses",
    skuCode: "DR-112",
    heroImage: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=520&q=60",
    tags: ["versatile", "commerce"],
  },
  {
    id: "prod-logo-tee",
    name: "Organic Logo Tee (Boxy Fit, Double Needle Hem)",
    styleName: "Relaxed",
    colourName: "Bone",
    category: "Tops",
    skuCode: "TP-041",
    heroImage: "https://images.unsplash.com/photo-1475180098004-ca77a66827be?auto=format&fit=crop&w=520&q=60",
    tags: ["ecom", "evergreen"],
  },
  {
    id: "prod-utility-pant",
    name: "Utility Pant with Reinforced Knee Panel",
    styleName: "Tapered",
    colourName: "Cacao",
    category: "Bottoms",
    skuCode: "BT-089",
    heroImage: "https://images.unsplash.com/photo-1475180098004-ca77a66827be?auto=format&fit=crop&w=520&q=60",
    tags: ["lookbook"],
  },
  {
    id: "prod-rain-shell",
    name: "Ultra Lightweight Packable Rain Shell — 3L Seam-Sealed, Stow Pocket",
    styleName: "Stormform 3L",
    colourName: "Glacial Fog",
    category: "Outerwear",
    skuCode: "RS-404",
    heroImage: "",
    tags: ["long-name", "packable", "no-image-fallback"],
  },
  {
    id: "prod-metallic-dress",
    name: "Metallic Bias-Cut Slip Dress (Holiday Capsule Limited)",
    styleName: "Mercury Bias",
    colourName: "Chromed Champagne",
    category: "Dresses",
    skuCode: "DR-777",
    heroImage: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=520&q=60",
    tags: ["holiday", "sparkle", "evening", "long-tag-names-are-fun"],
  },
];

export const demoTalent = [
  {
    id: "tal-lex",
    name: "Lex Harper",
    role: "Model",
    pronouns: "they/them",
    tags: ["movement", "edgy"],
  },
  {
    id: "tal-mia",
    name: "Mia Chen",
    role: "Model",
    pronouns: "she/her",
    tags: ["beauty", "commerce"],
  },
  {
    id: "tal-samir",
    name: "Samir Patel",
    role: "Model",
    pronouns: "he/him",
    tags: ["ecom", "studio"],
  },
  {
    id: "tal-nova",
    name: "Nova Ortiz",
    role: "Model",
    pronouns: "she/her",
    tags: ["movement", "athletic"],
  },
  {
    id: "tal-sky",
    name: "Sky Wilder",
    role: "Movement Director",
    pronouns: "she/they",
    tags: ["direction", "poses", "long-notes"],
  },
  {
    id: "tal-eli",
    name: "Eli van der Meer (art direction)",
    role: "Art Director",
    pronouns: "they/them",
    tags: ["notes-heavy", "references"],
  },
];

export const demoLocations = [
  {
    id: "loc-loft",
    name: "Canal St Daylight Loft",
    type: "Studio",
    address: "Canal St, NYC",
    notes: "South-facing windows for natural highlights.",
  },
  {
    id: "loc-greenhouse",
    name: "Glasshouse Studio",
    type: "Studio",
    address: "Greenpoint, Brooklyn",
    notes: "Plant-heavy set with controllable haze.",
  },
  {
    id: "loc-rooftop",
    name: "Mercer Rooftop",
    type: "Exterior",
    address: "SoHo, NYC",
    notes: "Great for golden hour skyline frames.",
  },
  {
    id: "loc-warehouse",
    name: "Pier 17 Industrial Warehouse with Loading Dock and Catwalk",
    type: "Industrial",
    address: "Seaport, NYC",
    notes: "High ceilings, sodium vapor overheads, tricky for mixed color temps.",
  },
  {
    id: "loc-beach",
    name: "Rockaway Beach Boardwalk (Windy Edge Case Location)",
    type: "Exterior",
    address: "Rockaway, Queens",
    notes: "Noise, sand, and wind — good for stress-testing UI labels.",
  },
];

export const demoProjects = [
  {
    id: "proj-citrus",
    name: "Citrus Glow SS25 — Sunlit Linen Story with Long Subtitle",
    shootDates: ["2025-03-04", "2025-03-06"],
    status: "active",
    notes: "Light-first creative with airy motion and citrus palette. Includes alt angles for reels, and overlapping deliverables per SKU.",
    stats: { shots: 8, shotsPlanned: 5, talent: 3, locations: 2 },
    updatedAt: "2025-02-12T10:00:00Z",
  },
  {
    id: "proj-denim",
    name: "Denim Refresh",
    shootDates: ["2025-03-12"],
    status: "active",
    notes: "Studio-first denim refresh with tighter hero crops.",
    stats: { shots: 5, shotsPlanned: 4, talent: 2, locations: 1 },
    updatedAt: "2025-02-10T14:10:00Z",
  },
  {
    id: "proj-holiday",
    name: "Holiday Lookbook — Evergreen + Sparkle Bundle",
    shootDates: ["2025-04-02", "2025-04-03"],
    status: "active",
    notes: "Cozy layering + sparkle micro-moments for paid social. Edge case: extra-long notes to test truncation in cards and tooltips.",
    stats: { shots: 6, shotsPlanned: 3, talent: 3, locations: 2 },
    updatedAt: "2025-02-08T09:00:00Z",
  },
  {
    id: "proj-internal",
    name: "Internal QA / Regression — Do Not Publish",
    shootDates: ["2025-02-20"],
    status: "archived",
    notes: "Used for regression. Ensure archived status pills & filters render correctly; includes shots with no talent and missing images.",
    stats: { shots: 3, shotsPlanned: 1, talent: 1, locations: 1 },
    updatedAt: "2025-02-05T12:00:00Z",
  },
];

export const demoShotsByProject = {
  "proj-citrus": [
    {
      id: "shot-citrus-hero",
      shotNumber: "S-01",
      name: "Hero look with citrus props and reflective scrim for rim light",
      type: "Wide hero with motion",
      status: "in_progress",
      date: "2025-03-04",
      locationId: "loc-loft",
      productIds: ["prod-linen-set", "prod-logo-tee"],
      talentIds: ["tal-lex", "tal-mia"],
      tags: [{ label: "hero" }, { label: "social" }, { label: "long-tag-name-for-wrapping" }],
      notes: "<p>Lead with natural daylight; add gentle fan for movement. Include both front and 45° angles.</p><ul><li>Edge: long copy wraps cell</li><li>Checklist: hero + detail</li></ul>",
      coverUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=60",
    },
    {
      id: "shot-citrus-flatlay",
      shotNumber: "S-02",
      name: "Flatlay with product grid",
      type: "Ecom + detail",
      status: "todo",
      date: "2025-03-04",
      locationId: "loc-loft",
      productIds: ["prod-logo-tee", "prod-utility-pant"],
      talentIds: [],
      tags: [{ label: "ecom" }],
      notes: "<p>Include SKU cards and call out stitching detail.</p>",
      coverUrl: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=60",
    },
    {
      id: "shot-citrus-video",
      shotNumber: "S-03",
      name: "15s motion loop",
      type: "Video",
      status: "on_hold",
      date: "2025-03-05",
      locationId: "loc-greenhouse",
      productIds: ["prod-linen-set"],
      talentIds: ["tal-lex"],
      tags: [{ label: "video" }],
      notes: "<p>Hold until final audio is cleared.</p>",
      coverUrl: "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=60",
    },
    {
      id: "shot-citrus-portrait",
      shotNumber: "S-04",
      name: "Tight portrait with citrus spill",
      type: "Portrait",
      status: "complete",
      date: "2025-03-05",
      locationId: "loc-loft",
      productIds: ["prod-knit-dress"],
      talentIds: ["tal-mia"],
      tags: [{ label: "paid-social" }],
      notes: "<p>Use haze for soft bloom.</p>",
      coverUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=60",
    },
    {
      id: "shot-citrus-staggered",
      shotNumber: "S-05",
      name: "Staggered trio with motion blur (extra wide name to wrap beautifully in table)",
      type: "Triptych",
      status: "todo",
      date: "2025-03-06",
      locationId: "loc-greenhouse",
      productIds: ["prod-linen-set", "prod-logo-tee", "prod-utility-pant"],
      talentIds: ["tal-lex", "tal-mia", "tal-samir"],
      tags: [{ label: "reel" }, { label: "carousel" }],
      notes: "<p>Test how multi-line names and long lists appear. Capture 120fps.</p>",
      coverUrl: "",
    },
  ],
  "proj-denim": [
    {
      id: "shot-denim-hero",
      shotNumber: "S-01",
      name: "Denim hero against seamless",
      type: "Studio hero",
      status: "in_progress",
      date: "2025-03-12",
      locationId: "loc-greenhouse",
      productIds: ["prod-denim-jacket", "prod-utility-pant"],
      talentIds: ["tal-samir"],
      tags: [{ label: "lookbook" }],
      notes: "<p>Keep lighting moody with edge light for texture.</p>",
      coverUrl: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=800&q=60",
    },
    {
      id: "shot-denim-detail",
      shotNumber: "S-02",
      name: "Denim detail stack",
      type: "Details",
      status: "todo",
      date: "2025-03-12",
      locationId: "loc-greenhouse",
      productIds: ["prod-denim-jacket"],
      talentIds: [],
      tags: [{ label: "ecom" }],
      notes: "<p>Call out buttons + top stitching.</p>",
      coverUrl: "https://images.unsplash.com/photo-1475180098004-ca77a66827be?auto=format&fit=crop&w=800&q=60",
    },
    {
      id: "shot-denim-motion",
      shotNumber: "S-03",
      name: "Spin move slow-mo",
      type: "Video",
      status: "todo",
      date: "2025-03-12",
      locationId: "loc-rooftop",
      productIds: ["prod-denim-jacket"],
      talentIds: ["tal-nova"],
      tags: [{ label: "social" }],
      notes: "<p>Capture wind with skyline background.</p>",
      coverUrl: "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=60",
    },
    {
      id: "shot-denim-rain",
      shotNumber: "S-04",
      name: "Rain shell stress test under water bars (outerwear edge case)",
      type: "Action",
      status: "on_hold",
      date: "2025-03-12",
      locationId: "loc-warehouse",
      productIds: ["prod-rain-shell"],
      talentIds: ["tal-eli"],
      tags: [{ label: "qa" }, { label: "packable" }],
      notes: "<p>Hold pending permits. Long product name to test pill width.</p>",
      coverUrl: "",
    },
  ],
  "proj-holiday": [
    {
      id: "shot-holiday-cozy",
      shotNumber: "S-01",
      name: "Cozy living room scene",
      type: "Lifestyle",
      status: "in_progress",
      date: "2025-04-02",
      locationId: "loc-loft",
      productIds: ["prod-knit-dress"],
      talentIds: ["tal-mia", "tal-samir"],
      tags: [{ label: "lifestyle" }],
      notes: "<p>Warm tungsten practicals; sprinkle faux snow on set.</p>",
      coverUrl: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=60",
    },
    {
      id: "shot-holiday-gift",
      shotNumber: "S-02",
      name: "Gift wrap macro",
      type: "Macro",
      status: "todo",
      date: "2025-04-03",
      locationId: "loc-loft",
      productIds: ["prod-logo-tee"],
      talentIds: [],
      tags: [{ label: "paid-social" }],
      notes: "<p>Metallic ribbon + brand sticker.</p>",
      coverUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=60",
    },
    {
      id: "shot-holiday-dress",
      shotNumber: "S-03",
      name: "Metallic slip dress sparkle pass (with glitter fallout cleanup)",
      type: "Editorial",
      status: "complete",
      date: "2025-04-03",
      locationId: "loc-rooftop",
      productIds: ["prod-metallic-dress"],
      talentIds: ["tal-nova"],
      tags: [{ label: "sparkle" }],
      notes: "<p>Ensure glitter doesn't blow onto camera — another edge case.</p>",
      coverUrl: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=800&q=60",
    },
  ],
  "proj-internal": [
    {
      id: "shot-internal-empty",
      shotNumber: "QA-01",
      name: "Placeholder shot with no image",
      type: "System regression",
      status: "todo",
      date: "2025-02-20",
      locationId: "loc-beach",
      productIds: ["prod-rain-shell"],
      talentIds: [],
      tags: [{ label: "edge" }, { label: "empty-state" }],
      notes: "<p>Edge case: zero attachments, empty talent array.</p>",
      coverUrl: "",
    },
    {
      id: "shot-internal-longtext",
      shotNumber: "QA-02",
      name: "Extremely long shot title to force overflow and wrapping in the table view when testing the demo mode layout for Stitch",
      type: "Copy stress",
      status: "in_progress",
      date: "2025-02-20",
      locationId: "loc-warehouse",
      productIds: ["prod-utility-pant", "prod-linen-set"],
      talentIds: ["tal-lex"],
      tags: [{ label: "long-text" }],
      notes: "<p>Long paragraph: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>",
      coverUrl: "",
    },
    {
      id: "shot-internal-complete",
      shotNumber: "QA-03",
      name: "Completed shot to surface 'complete' pill in archived project",
      type: "Archival",
      status: "complete",
      date: "2025-02-20",
      locationId: "loc-loft",
      productIds: ["prod-logo-tee"],
      talentIds: ["tal-eli"],
      tags: [{ label: "archived" }],
      notes: "<p>Should still render even if project is archived.</p>",
      coverUrl: "",
    },
  ],
};

export const demoPulls = [
  {
    id: "pull-01",
    name: "Daylight hero kit",
    projectId: "proj-citrus",
    status: "published",
    shared: true,
    shareToken: "demo-share-token",
    items: [
      { productId: "prod-linen-set", quantity: 2, notes: "Bring steamed + backup" },
      { productId: "prod-logo-tee", quantity: 3, notes: "One in XS for tight tuck" },
    ],
  },
  {
    id: "pull-02",
    name: "Denim studio cart with backups and alt colorway",
    projectId: "proj-denim",
    status: "draft",
    shared: false,
    items: [
      { productId: "prod-denim-jacket", quantity: 2, notes: "One raw, one worn-in" },
      { productId: "prod-utility-pant", quantity: 2, notes: "Steam onsite" },
    ],
  },
  {
    id: "pull-03",
    name: "Regression pull (archive-safe)",
    projectId: "proj-internal",
    status: "archived",
    shared: false,
    items: [
      { productId: "prod-rain-shell", quantity: 1, notes: "Edge: no image" },
      { productId: "prod-linen-set", quantity: 1, notes: "Edge: long name" },
    ],
  },
];

export const demoActivities = [
  {
    id: "activity-1",
    projectId: "proj-citrus",
    summary: "Lex marked “Hero look with citrus props” as In progress",
    detail: "Status changed from Todo to In progress",
    actor: "Lex Harper",
    createdAt: "2025-02-12T09:32:00Z",
  },
  {
    id: "activity-2",
    projectId: "proj-denim",
    summary: "Mia added styling notes to Denim hero",
    detail: "Pinned reference image to keep collar structure.",
    actor: "Mia Chen",
    createdAt: "2025-02-11T16:12:00Z",
  },
  {
    id: "activity-3",
    projectId: "proj-holiday",
    summary: "Samir duplicated Cozy living room scene",
    detail: "New alt angle for paid social.",
    actor: "Samir Patel",
    createdAt: "2025-02-10T10:48:00Z",
  },
  {
    id: "activity-4",
    projectId: "proj-internal",
    summary: "QA updated long-title shot status to Complete",
    detail: "Regression coverage for archived projects.",
    actor: "QA Bot",
    createdAt: "2025-02-05T12:30:00Z",
  },
];
