name: gitleaks
on:
  pull_request:
  push:
jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write  # allow upload to code scanning
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install gitleaks CLI
        run: |
          set -euo pipefail
          VER=8.24.3
          URL="https://github.com/gitleaks/gitleaks/releases/download/v${VER}/gitleaks_${VER}_linux_x64.tar.gz"
          curl -sSL "$URL" -o gitleaks.tgz
          tar -xzf gitleaks.tgz
          sudo mv gitleaks /usr/local/bin/gitleaks
          gitleaks version

      - name: Scan (PR) — working tree only (blocking)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          gitleaks detect \
            --source . \
            --no-git \
            --redact \
            --report-format sarif \
            --report-path gitleaks-results.sarif \
            --config .github/gitleaks.toml

      - name: Scan (push) — include history (non-blocking)
        if: ${{ github.event_name == 'push' }}
        run: |
          gitleaks detect \
            --source . \
            --redact \
            --report-format sarif \
            --report-path gitleaks-results.sarif \
            --config .github/gitleaks.toml || true

      - name: Ensure SARIF exists
        if: ${{ always() }}
        run: |
          if [ ! -f gitleaks-results.sarif ]; then
cat > gitleaks-results.sarif <<'JSON'
{
  "version": "2.1.0",
  "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
  "runs": [{
    "tool": {"driver": {"name": "gitleaks", "version": "8.24.3"}},
    "results": []
  }]
}
JSON
          fi

      - name: Upload gitleaks SARIF (artifact)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-results.sarif
          path: gitleaks-results.sarif
          if-no-files-found: warn

      - name: Upload SARIF to code scanning
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks-results.sarif
          category: gitleaks-cli
