name: Tests

on:
  pull_request:
  push:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash -Eeuo pipefail {0}'

jobs:
  vitest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      # Provide Firebase env to avoid any import-time failures when files reference env.
      VITE_FIREBASE_API_KEY:             ${{ secrets.VITE_FIREBASE_API_KEY || 'test-key' }}
      VITE_FIREBASE_AUTH_DOMAIN:         ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN || 'test.firebaseapp.com' }}
      VITE_FIREBASE_PROJECT_ID:          ${{ secrets.VITE_FIREBASE_PROJECT_ID || 'test-project' }}
      VITE_FIREBASE_STORAGE_BUCKET:      ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET || 'test.appspot.com' }}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID || '1234567890' }}
      VITE_FIREBASE_APP_ID:              ${{ secrets.VITE_FIREBASE_APP_ID || '1:123:web:abc' }}
      VITE_FIREBASE_MEASUREMENT_ID:      ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20 LTS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run tests
        run: npm test

